[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=61.0"]



[project]
# https://packaging.python.org/en/latest/specifications/declaring-project-metadata/
name = "iraklis7_ubp"
version = "1.1.4"
description = "Utility Bill Processor"
readme = "README.md"
requires-python = ">=3.9,<4.0"
# "LICENSE" is name of the license file, which must be in root of project folder
license = "MIT"
authors = [
    {name = "Iraklis Diamantidis", email = "iraklis.diamantidis@gmail.com"},
]
keywords = ["utility", "bill"]
dependencies = [
  "landingai_ade",
  "pydantic",
  "pathlib%"
]

[tool.hatch.build.targets.sdist]
# Basically everything except hidden files/directories (such as .github, .devcontainers, .python-version, etc)
include = [
  "output/*",
  "src/*",
  "tests/*",
  "/*.md",
  "/*.txt"
]