[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=61.0"]


[project]
# https://packaging.python.org/en/latest/specifications/declaring-project-metadata/
name = "iraklis7_ubp"
version = "1.0.1"
description = "Utility Bill Processor"
readme = "README.md"
requires-python = ">=3.9,<4.0"
# "LICENSE" is name of the license file, which must be in root of project folder
license = "MIT"
authors = [
    {name = "Iraklis Diamantidis", email = "iraklis.diamantidis@gmail.com"},
]
keywords = ["utility", "bill"]
